#!/bin/tcsh -f
set mppnccombine=/autofs/na2_home2/fms/local/opt/fre-nctools/bronx-4/ncrc2/bin/mppnccombine
set outputDir=`pwd`/..
set begdate = tmp`date '+%j%H%M%S'`

set asciiFiles = ( `/bin/ls -1 *.out` )
if ( $#asciiFiles > 0 ) then
if ( ! -d $outputDir/ascii ) mkdir -p $outputDir/ascii
foreach file ( $asciiFiles )
mv $file $outputDir/ascii/$begdate.$file
end
endif

set historyFiles = ( `/bin/ls -1 4xday*.0000` )

if ( $#historyFiles > 0 ) then
if ( ! -d $outputDir/history ) mkdir -p $outputDir/history
foreach file ( $historyFiles )
$mppnccombine -64 $file:r $file:r.????
endif

set historyFiles = ( `/bin/ls -1 1x20days*.0000` )

if ( $#historyFiles > 0 ) then
if ( ! -d $outputDir/history ) mkdir -p $outputDir/history
foreach file ( $historyFiles )
$mppnccombine -64 $file:r $file:r.????
endif
